<!-- Automagically generated by 'jsdocs' -->
<template>
  <div id="review-page" class="container">
    <div class="review-page row">
      <ReviewBlock :reviews="content.reviews.data"/>
    </div>
  </div>
</template>

<script>
import ReviewBlock from "./../components/ReviewBlock";

export default {
  name: "Review",
  components: {
    ReviewBlock
  },
  props: ["content"],
  meta() {
    return {
      title: "Review",
      description: "This is the meta description for the review page"
    };
  },
  data: function() {
    return {};
  },
  methods: {}
};
</script>

<style>
* {
  box-sizing: border-box;
}
</style>
